{% set version = '1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bootsvd
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bootSVD_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bootSVD/bootSVD_{{ version }}.tar.gz
  sha256: 29eeabd85c47c284f655093399c4ba96b0aad958933eb776a2dbc1bfd1c6a399

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ff
  run:
    - r-base
    - r-ff

test:
  commands:
    - $R -e "library('bootSVD')"           # [not win]
    - "\"%R%\" -e \"library('bootSVD')\""  # [win]

about:
  home: http://arxiv.org/abs/1405.0922
  license: GPL-2.0-only
  summary: Implements fast, exact bootstrap Principal Component Analysis and Singular Value Decompositions
    for high dimensional data, as described in <doi:10.1080/01621459.2015.1062383> (see
    also <arXiv:1405.0922> ). For data matrices that are too large to operate on in
    memory, users can input objects with class 'ff' (see the 'ff' package), where the
    actual data is stored on disk. In response, this package will implement a block
    matrix algebra procedure for calculating the principal components (PCs) and bootstrap
    PCs. Depending on options set by the user, the 'parallel' package can be used to
    parallelize the calculation of the bootstrap PCs.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - TCLamnidis

# Package: bootSVD
# Title: Fast, Exact Bootstrap Principal Component Analysis for High Dimensional Data
# Description: Implements fast, exact bootstrap Principal Component Analysis and Singular Value Decompositions for high dimensional data, as described in <doi:10.1080/01621459.2015.1062383> (see also <arXiv:1405.0922> ). For data matrices that are too large to operate on in memory, users can input objects with class 'ff' (see the 'ff' package), where the actual data is stored on disk. In response, this package will implement a block matrix algebra procedure for calculating the principal components (PCs) and bootstrap PCs. Depending on options set by the user, the 'parallel' package can be used to parallelize the calculation of the bootstrap PCs.
# Version: 1.1
# Author: Aaron Fisher <afishe27@alumni.jh.edu>
# Maintainer: Aaron Fisher <afishe27@alumni.jh.edu>
# URL: http://arxiv.org/abs/1405.0922
# Depends: R (>= 3.0.2)
# Imports: ff, parallel
# License: GPL-2
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2021-02-01 22:28:49 UTC; aaronfisher
# Repository: CRAN
# Date/Publication: 2021-02-02 10:20:12 UTC
